# Define default settings that will be applied to all services
x-service-defaults: &service-defaults
  deploy:
    restart_policy:
      condition: "none"
  labels:
    - "com.docker.compose.rm=true"

volumes:
  ql_dvol:

services:
  volume-setup: ##  TODO, this is likely not need, change to the "list content" service
    <<: *service-defaults
    image: alpine:latest
    volumes:
      - ql_dvol:/data
    command: chown -R 1000:1000 /data
    user: root

  downloader:
    <<: *service-defaults
    image: alpine/curl
    depends_on:
      volume-setup:
        condition: service_completed_successfully
    user: "1000:1000" # Add this line to run as the same user
    volumes:
      - ql_dvol:/data
      - ${PWD}:/tmp/localdata:ro
    command: >
      sh -c "cp /tmp/localdata/Qleverfile /data &&
      cp /tmp/localdata/Qleverfile-ui.yml  /data  &&
      ls -l /data && echo 'Files copied to /data/'"

  getsql:
    <<: *service-defaults
    image: adfreiburg/qlever-ui:latest
    depends_on:
      downloader:
        condition: service_completed_successfully
    user: "1000:1000"
    volumes:
      - ql_dvol:/data
    #    working_dir: /data
    command: >
      sh -c "cp /app/db/qleverui.sqlite3 /data/odis-qleverui.sqlite3 &&
          chown 1000 /data/odis-qleverui.sqlite3 &&
          chmod 666 /data/odis-qleverui.sqlite3 &&
          ls -l /data && echo 'Files in /data/'"
    stdin_open: true
    tty: true

  getdata:
    <<: *service-defaults
    image: adfreiburg/qlever:latest
    depends_on:
      getsql:
        condition: service_completed_successfully
    user: "1000:1000"
    volumes:
      - ql_dvol:/data
    working_dir: /data
    command: ["qlever -q Qleverfile get-data"]
    stdin_open: true
    tty: true

  indexer:
    <<: *service-defaults
    image: adfreiburg/qlever:latest
    depends_on:
      getdata:
        condition: service_completed_successfully
    user: "1000:1000"
    volumes:
      - ql_dvol:/data
    working_dir: /data
    command:
      [
        "qlever -q Qleverfile index --system native --overwrite-existing  --text-index  from_text_records_and_literals",
      ]
    stdin_open: true
    tty: true

  report:
    <<: *service-defaults
    image: alpine/curl
    depends_on:
      indexer:
        condition: service_completed_successfully
    user: "1000:1000" # Add this line to run as the same user
    volumes:
      - ql_dvol:/data
    command: >
      sh -c "ls -l /data && cat /data/odis.settings.json && cat /data/Qleverfile"
